### ISSUE TITLE
Add Quick Sort Algorithm in C++

### ISSUE THREAD

**Issue by jay13makhija** [jay13makhija/Algorithms#8]

**Comment by SrishtiDharwani** [comment]
@jay13makhija  I can work on this!

**Comment by jay13makhija** [comment]
Fork and work on it and then directly send a pull request
NO ONE WILL BE ASSIGNED IN PERTICULAR FOR THIS ISSUE

**Comment by SrishtiDharwani** [comment]
@jay13makhija  done
