### ISSUE TITLE
Add Kadane's Algorithm implemented in C++

### ISSUE THREAD

**Issue by jay13makhija** [jay13makhija/Algorithms#9]

**Comment by ankitkumar0622** [comment]
Hey , can you please assign this to me ? I would love to work on this

**Comment by jay13makhija** [comment]
Fork and work on it and then directly send a pull request
NO ONE WILL BE ASSIGNED IN PERTICULAR FOR THIS ISSUE

**Comment by ankitkumar0622** [comment]
Ok

**Comment by ankitkumar0622** [comment]
Hey there, ive added the Kadanes Algorithm and made a pull request can you please have a look ...
